on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: self-hosted
    steps:
    - name: Run script file
      run: |
         echo "this is demo" >>/home/ubuntu/demo.txt
      shell: bash
